# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/Nexys-A7-100t-Master.xdc

# IP: ip/VideoMemory/VideoMemory.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==VideoMemory || ORIG_REF_NAME==VideoMemory} -quiet] -quiet
