# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Nexys-A7-100t-Master.xdc

# IP: ip/ClockingWizard/ClockingWizard.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ClockingWizard || ORIG_REF_NAME==ClockingWizard} -quiet] -quiet
