# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Wout/Documents/School/3 digitale Elektronica/project1/mem/VideoMemory.xci
# IP: The module: 'VideoMemory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Wout/Documents/School/3 digitale Elektronica/project1/mem/VideoMemory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VideoMemory'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Wout/Documents/School/3 digitale Elektronica/project1/mem/VideoMemory.xci
# IP: The module: 'VideoMemory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Wout/Documents/School/3 digitale Elektronica/project1/mem/VideoMemory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VideoMemory'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
